import { ACCEPTED_TOKENS_RECORDS, CIL_TOKEN_RECORDS } from "./tokens";
import { PROVIDER_RECORDS, EXPLORER_RECORDS, NETWORK } from "./common/config";
import {
  START_TIME,
  CLOSE_TIME,
  CLI_PRICE,
  HARD_CAP,
  PRESALE_ADDRESS_RECORDS,
  PRESALE_WHITELIST_RECORDS,
} from "./presale";
import {
  AIRDROP_CONTRACT_ADDRESS_RECORDS,
  AIRDROP_WHITELIST_RECORDS,
} from "./airdrop";

const ACCEPTED_TOKENS = ACCEPTED_TOKENS_RECORDS[NETWORK];
const CIL_TOKEN = CIL_TOKEN_RECORDS[NETWORK];
const PROVIDER = PROVIDER_RECORDS[NETWORK];
const EXPLORER = EXPLORER_RECORDS[NETWORK];
const AIRDROP_CONTRACT_ADDRESS = AIRDROP_CONTRACT_ADDRESS_RECORDS[NETWORK];
const AIRDROP_WHITELIST = AIRDROP_WHITELIST_RECORDS[NETWORK];
const PRESALE_WHITELIST = PRESALE_WHITELIST_RECORDS[NETWORK];
const PRESALE_ADDRESS = PRESALE_ADDRESS_RECORDS[NETWORK];

export {
  ACCEPTED_TOKENS,
  CIL_TOKEN,
  PROVIDER,
  EXPLORER,
  NETWORK,
  START_TIME,
  CLOSE_TIME,
  CLI_PRICE,
  HARD_CAP,
  AIRDROP_CONTRACT_ADDRESS,
  AIRDROP_WHITELIST,
  PRESALE_WHITELIST,
  PRESALE_ADDRESS,
};
